### PR TITLE
Rest creation2.0

### PR DESCRIPTION
**Pull request by carlosCabrera2**
-Cocktails Repository creation
-CocktailApi creation
-modification of UIState to add Generic "T"

CC

### CODE REVIEW

**Comment by inaki92** [comment]
@carlosCabrera2  you are merging to MAIN

**Review by sarisiza — DISMISSED** [review]
LGTM

**Review by luizeth0 — APPROVED** [review]
LGTM!

**Review by sarisiza — APPROVED** [review]
LGTM

**Review by chr1s4ng3l — APPROVED** [review]
lgtm

**Pull request merged**
